import car1newImage from "@/assets/bookNowImages/newImages/1.jpg";
import car2newImage from "@/assets/bookNowImages/newImages/2.jpg";
import car3newImage from "@/assets/bookNowImages/newImages/3.jpg";

export const carFilterConfig = [
  {
    carName: "Peugeot 108 automatic",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car1newImage,
    date: "2024-06-10",
  },
  {
    carName: "Citroen C3",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3400,
      onDesk: 3675,
    },
    carImage: car2newImage,
    date: "2024-06-06",
  },
  {
    carName: "Fiat Panda",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3200,
      onDesk: 3500,
    },
    carImage: car3newImage,
    date: "2024-06-01",
  },
  {
    carName: "Peugeot 108 automatic",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car1newImage,
    date: "2024-05-28",
  },
  {
    carName: "Citroen C3",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3400,
      onDesk: 3675,
    },
    carImage: car2newImage,
    date: "2024-05-20",
  },
  {
    carName: "Fiat Panda",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3200,
      onDesk: 3500,
    },
    carImage: car3newImage,
    date: "2024-05-15",
  },
  {
    carName: "Peugeot 108 automatic",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car1newImage,
    date: "2024-05-10",
  },
  {
    carName: "Citroen C3",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3400,
      onDesk: 3675,
    },
    carImage: car2newImage,
    date: "2024-05-05",
  },
  {
    carName: "Fiat Panda",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3200,
      onDesk: 3500,
    },
    carImage: car3newImage,
    date: "2024-05-01",
  },
];
