import car1newImage from "@/assets/bookNowImages/newImages/1.jpg";
import car2newImage from "@/assets/bookNowImages/newImages/2.jpg";
import car3newImage from "@/assets/bookNowImages/newImages/3.jpg";

export const carFilterConfig = [
  {
    carName: "Peugeot 108 automatic",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car1newImage,
  },
  {
    carName: "Citroen C3",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car2newImage,
  },
  {
    carName: "Fiat Panda",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car3newImage,
  },
  {
    carName: "Peugeot 108 automatic",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car1newImage,
  },
  {
    carName: "Citroen C3",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car2newImage,
  },
  {
    carName: "Fiat Panda",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car3newImage,
  },
  {
    carName: "Peugeot 108 automatic",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car1newImage,
  },
  {
    carName: "Citroen C3",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car2newImage,
  },
  {
    carName: "Fiat Panda",
    similarCarOptions: [],
    carClass: "A",
    fuelType: "Unleaded",
    doors: 4,
    personCary: 4,
    bagCary: 1,
    IsAc: true,
    bookingPrice: {
      online: 3600,
      onDesk: 3876,
    },
    carImage: car3newImage,
  },
];
